### ISSUE TITLE
Commentable database behavior not working on mysql view

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework-comments#5]
Commentable behavior is not working properly when using mysql view.

When a component has a mysql view, its name is set in the table config hence `$this->getTable()->getName()` returns the name of the view. I think we should use `getBase()` instead.

**Comment by johanjanssens** [comment]
@jebbdomingo @raeldc We don't use mysql views anymore in any of our code. Stopped using that approach. Are comments still using views ?

**Comment by jebbdomingo** [comment]
@johanjanssens DESKman is using mysql view for tickets to support `reporter_name` and `assignee_name` columns, in table config the `name` is set to the view's name and `base` with the actual `support_tickets` table. com:comments's `commentable` behavior is utilized in DESKman, since it's in the context of the ticket its use of getTable()->getName() returns the tickets' view instead of the table.

**Comment by johanjanssens** [comment]
There is no need to create a view here. Since we renamed the component to DESKman the database tables also need to be renamed to match this convention. So it would be deskman_tickets and not support_tickets. This will prevent you to need a view. The reporter name and assignee names can be solved differently, see my other comments on how to do that best. /cc @raeldc

**Comment by jebbdomingo** [comment]
@johanjanssens alright then should we close this as invalid?

**Comment by johanjanssens** [comment]
Yes we can. Just make sure to remove the MySQL view support and implementation from DESKman.
